# Generated by Django 5.2.5 on 2025-10-31 12:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0096_alter_user_language_code'),
        ('product', '0202_category_product_category_tree_id_lf1e1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(help_text='Рейтинг от 1 до 5 звезд', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(help_text='Текст отзыва')),
                ('is_published', models.BooleanField(default=False, help_text='Опубликован ли отзыв (после модерации)')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='product_reviews/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='product_reviews/')),
                ('moderated_by', models.ForeignKey(blank=True, help_text='Оператор, который отмодерировал отзыв', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to='account.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='account.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'is_published'], name='product_pro_product_b4e5f0_idx'), models.Index(fields=['user'], name='product_pro_user_id_270cc2_idx')],
            },
        ),
    ]
